---
title: "R Notebook"
output: html_notebook
---

```{r echo=FALSE, message=FALSE}
library(MM4LMM)
library(sommer)
library(nnet)
library(Eagle)
library(parallel)
library(dplyr)
# library(tidyverse)

source("Eagle_Multi_Genomes.R")
```

#### load DT data

```{r}
data(DT_technow)
DT <- DT_technow

Mf <- Mf_technow
Md <- Md_technow

Zf <- class.ind(DT$flint)
Zf <- Zf[,rownames(Mf)]

Zd <- class.ind(DT$dent)
Zd <- Zd[,rownames(Md)]
```

#### simulation

```{r}
# h <- c(0.1, 0.3, 0.5, 0.7, 0.9)
h <- c(0.5, 0.7, 0.9)

PWD <- paste0(getwd(),"/Test_Result05/")
label <- "[ad_=%d][af_=%d][gamma=%.2f][h=%.2f][Poly.size.d=%d][Poly.size.f=%d][Poly.effet.d=%.3f][Poly.effet.f=%.3f][tn=%d]"
simulation_times <- 100
max_itr_num <- 50
gamma <- 0.0
# ad_ <- 5 # change to 10 
# af_ <- 5 # change to 10 

ad_ <-10 # fixed
af_ <-10 # fixed 

nqtl.d = 10 # fixed
nqtl.f = 10 # fixed

Freq.d <- colMeans(Md)
Freq.f <- colMeans(Mf)

Informative.d <- which(Freq.d>10/nrow(Md) & Freq.d< 1- 10/nrow(Md))
Informative.f <- which(Freq.f>10/nrow(Mf) & Freq.f< 1- 10/nrow(Mf))
    
Poly.size.d <- 10000 # fixed
Poly.size.f <- 10000 # fixed

Poly.effet.d <- 1
Poly.effet.f <- 1

save_model <- function(Sd, Sf, adS, afS, ad_S, af_S, E = E, fname) {
  saveRDS(object = list("E" = E, "Sd" = Sd, "Sf" = Sf, 
                        "adS" = adS, "afS" = afS, 
                        "ad_S" = ad_S, "af_S" = af_S), file = fname)
}

save_trait <- function(Y, fname) {
  write.table(list("Trait" = Y), file = fname, 
              row.names =  FALSE, sep = " ", quote = FALSE)
}

sl_label <- function(h, tn) return(sprintf(label, ad_, af_, gamma, h, Poly.size.d, Poly.size.f, Poly.effet.d, Poly.effet.f, tn))

model_fname <- function(h, tn) {
  return(paste0(PWD, "model_", sl_label(h,tn), ".rds"))
}

trait_fname <- function(h, tn) {
  return(paste0(PWD, "trait_", sl_label(h,tn), ".dat"))
}

sl <- function (h, tn) {
  
  while(TRUE) {
    Sd <- sample(Informative.d, nqtl.d)
    Sf <- sample(Informative.f, nqtl.f)
    
    MdS <- Md[, Sd]
    MfS <- Mf[, Sf]
    
    Md_S <- Md[, -Sd]
    Mf_S <- Mf[, -Sf]
    
    ad_S <- rep(0,ncol(Md_S))
    af_S <- rep(0,ncol(Mf_S))

    ad_S[sample(1:length(ad_S), Poly.size.d)] <- runif(min = -Poly.effet.d, max = Poly.effet.d, n = Poly.size.d)
    af_S[sample(1:length(af_S), Poly.size.f)] <- runif(min = -Poly.effet.f, max = Poly.effet.f, n = Poly.size.f)
      
    adS <- seq(ad_,ad_+nqtl.d,l=nqtl.d)
    afS <- seq(af_,af_+nqtl.f,l=nqtl.f)
    
    Ud <- MdS %*% adS + Md_S %*% ad_S
    Uf <- MfS %*% afS + Mf_S %*% af_S
    
    Uh <- Zd %*% Ud + Zf %*% Uf
    Ua <- Zd %*% MdS %*% adS + Zf %*% MfS %*% afS 
    
    vg <- var(Uh)
    va <- var(Ua)
    
    a_ratio <- va/vg
    
    if (a_ratio < 0.17 && a_ratio > 0.13) {
      sigma_E <- as.numeric(sqrt(vg*(1-h)/h))
      E <- sigma_E * rnorm(length(DT$GY))
      Y <- Uh + E
      
      save_model(Sd = Sd, Sf = Sf, adS = adS, afS = afS, 
                 ad_S = adS, af_S = af_S, E = E, fname = model_fname(h,tn))
      
      save_trait(Y, fname = trait_fname(h,tn))
      
      return(a_ratio)
    }
  }
}

mcmapply(sl, h = rep(h, each = simulation_times), tn = rep(1:simulation_times, length(h)), mc.cores = getOption("mc.cores", 48L))

```


```{r}

simu <- function (a_) {
  Freq.d <- colMeans(Md)
  Freq.f <- colMeans(Mf)
 
  Informative.d <- which(Freq.d>10/nrow(Md) & Freq.d< 1- 10/nrow(Md))
  Informative.f <- which(Freq.f>10/nrow(Mf) & Freq.f< 1- 10/nrow(Mf))
 
  Sd <- sample(Informative.d, nqtl.d)
  Sf <- sample(Informative.f, nqtl.f)
 
  MdS <- Md[, Sd]
  MfS <- Mf[, Sf]
 
  Md_S <- Md[, - Sd]
  Mf_S <- Mf[, - Sf]
 
  ad_S <- rep(0,ncol(Md_S))
  af_S <- rep(0,ncol(Mf_S))
 
  Poly.effet.d <- 1 # c(0.1, 0.01)
  Poly.effet.f <- 1 # c(0.1, 0.01)
 
  ad_S[sample(1:length(ad_S), 20000)] <- runif(min = -Poly.effet.d, max = Poly.effet.d, n = 20000)
  af_S[sample(1:length(af_S), 20000)] <- runif(min = -Poly.effet.f, max = Poly.effet.f, n = 20000)
    
  adS <- seq(a_,a_+nqtl.d,l=nqtl.d)
  afS <- seq(a_,a_+nqtl.f,l=nqtl.f)
 
  Ud <- MdS %*% adS + Md_S %*% ad_S
  Uf <- MfS %*% afS + Mf_S %*% af_S
 
  Uh <- Zd %*% Ud + Zf %*% Uf
  Ua <- Zd %*% MdS %*% adS + Zf %*% MfS %*% afS
 
  vh <- var(Uh)
  va <- var(Ua)
  if (va/vh < 0.2) return(a_)
}

unlist(mclapply(1:100, simu, mc.cores = getOption("mc.cores", 48L))) 
```


```{r echo=FALSE, message=FALSE}

test_case <- function(h, tn) {
    
  if (DO_EAGLE) {
    # tfname = paste0(PWD, "eagle_resultat_", sl_label(h, tn))
    # if (!file.exists(tfname)) {
      phenoObj <- ReadPheno(paste0(trait_fname(h,tn)))
      Mf_genoObj <- ReadMarker(paste0(PWD,"Mf.dat"), type = "text", AA = 0, AB = 2, BB = 1)
      Md_genoObj <- ReadMarker(paste0(PWD,"Md.dat"), type = "text", AA = 0, AB = 2, BB = 1)
      
      Mf_Zmat <- ReadZmat(paste0(PWD,"Zf.dat"))
      Md_Zmat <- ReadZmat(paste0(PWD,"Zd.dat"))
      
      eagle_start_time <- Sys.time()
      Eagle_selected_locus_G1 <- AM(trait = "Trait", Zmat = Mf_Zmat, geno = Mf_genoObj, 
                                    pheno = phenoObj, ncpu = 48, lambda = gamma, maxit = ceiling(max_itr_num/2), fixit = TRUE)
      Eagle_selected_locus_G2 <- AM(trait = "Trait", Zmat = Md_Zmat, geno = Md_genoObj, 
                                    pheno = phenoObj, ncpu = 48, lambda = gamma, maxit = ceiling(max_itr_num/2), fixit = TRUE)
      eagle_end_time <- Sys.time()
      
      saveRDS(list("Eagle_selected_locus_G1" = Eagle_selected_locus_G1$Indx, 
                   "Eagle_selected_locus_G2" = Eagle_selected_locus_G2$Indx, 
                   "eagle_excute_time" = eagle_end_time - eagle_start_time), 
              file = paste0(PWD, "Eagle_Results/eagle_resultat_", sl_label(h,tn)))
    # }
  }
  
  if (DO_EMG) {

    # if (!file.exists(tfname)) {
      
      Y <- read.csv(trait_fname(h,tn), sep = " ", header = TRUE)[,1]
        
      emg_start_time <- Sys.time()
      EMG_selected_locus <- EMG(Y = Y, G1 = Mf_technow*2, G2 = Md_technow*2, Z1 = Zf, Z2 = Zd, 
                  genome_names = c("Flint", "Dent"), gamma = gamma, max_itr_num = max_itr_num )
      emg_end_time <- Sys.time()
        
      saveRDS(list("EMG_selected_locus" = EMG_selected_locus, 
                     "emg_excute_time" = emg_end_time - emg_start_time), 
                  file = paste0(PWD, "EMG_Results/emg_resultat_", sl_label(h,tn)))
    # }
  }
}

```

```{r}

DO_EMG = TRUE
DO_EAGLE = FALSE
simulation_times <- 50
mcmapply(test_case, h = rep(h, each = simulation_times), tn = rep(1:simulation_times, length(h)), mc.cores = getOption("mc.cores", 12L))

DO_EMG = FALSE
DO_EAGLE = TRUE
simulation_times <- 10
args_X <- data.frame("h" = rep(h, each = simulation_times), "tn" = rep(1:simulation_times, length(h)))

for (i in 1:dim(args_X)[1]) {
  test_case(h = args_X[i,]$h,tn = args_X[i,]$tn)
}

```

#### courbe de nombre de TP en fonction de snps sélectionnés 

```{r}
h = 0.9
max_trancate_num <- 50

eagle_total_test_times <- 10
emg_total_test_times   <- 20

nhbrhd <- function(S, nb_radius=5) unlist(lapply(S, function(x){seq(x-nb_radius,x+nb_radius)}))

trancate_eagle_result <- function(G1, G2, nmb_qtl) {

  if (nmb_qtl >= length(G1)+length(G2)) {
    return(list("G1" = G1, "G2" = G2))
  }
  
  # if (length)
  
  G1_count = ceiling(nmb_qtl/2)
  
  if (G1_count < length(G1)) {
    return(list("G1" = G1[1:G1_count], "G2" = G2[1:(nmb_qtl - G1_count)]))
  }
  
  tryCatch({
    return(list("G1" = G1, "G2" = G2[1:(nmb_qtl-length(G1))]))
  }, error = function(cond) {
    print(cond)
    print(sprintf("length(G1): %d, length(G2): %d, nmb_qtl: %d",length(G1), length(G2), nmb_qtl))
  })
}

trancate_emg_result <- function(G1, G2, selection_order, nmb_qtl) {
  if (nmb_qtl >= length(selection_order)) {
    return(list("G1" = G1, "G2" = G2))
  }
  
  G1_count = sum(selection_order[1:nmb_qtl] == 1)
  
  if (G1_count == 0) return(list("G1" = c(), "G2" = G2[1:nmb_qtl]))
  if (G1_count == nmb_qtl) return(list("G1" = G1[1:G1_count], "G2" = c()))
  return(list("G1" = G1[1:G1_count], "G2" = G2[1:(nmb_qtl-G1_count)]))
}

eagle_TP1_list = list()
eagle_TP2_list = list()

eagle_TP_list = list()

eagle_FP_list <- list()
eagle_FN_list <- list()

emg_TP1_list <- list()
emg_TP2_list <- list()

emg_TP_list <- list()

emg_FP_list <- list()
emg_FN_list <- list()

for (trancate_idx in 1:max_trancate_num) {
  
    # print(trancate_idx)
    
    eagle_TP1 <- c()
    eagle_TP2 <- c()
    
    eagle_FP <- c()
    eagle_FN <- c()
  
    emg_TP1 <- c()
    emg_TP2 <- c()
    
    emg_FP <- c()
    emg_FN <- c()
    
    for (tn in 1:eagle_total_test_times) {
      
      res_eagle <- readRDS(file = paste0(PWD, "Eagle_Results/eagle_resultat_", sl_label(h,tn)))
      mdl <- readRDS(model_fname(h,tn))
  
      Sd  <- mdl$Sd
      Sf  <- mdl$Sf
      
      Sd_neighborhood <- nhbrhd(Sd, 100)
      Sf_neighborhood <- nhbrhd(Sf, 100)
      
      trancated_eagle_res <- trancate_eagle_result(G1 = res_eagle$Eagle_selected_locus_G1[2:length(res_eagle$Eagle_selected_locus_G1)],
                                                   G2 = res_eagle$Eagle_selected_locus_G2[2:length(res_eagle$Eagle_selected_locus_G2)],
                                                   nmb_qtl = trancate_idx)
  
      eagle_TP1 <- c(eagle_TP1, length(intersect(unlist(Sf_neighborhood), trancated_eagle_res$G1)))
      eagle_TP2 <- c(eagle_TP2, length(intersect(unlist(Sd_neighborhood), trancated_eagle_res$G2)))
    }
    
    for (tn in 1:emg_total_test_times) {
      
      res_emg <- readRDS(file = paste0(PWD, "EMG_Results/emg_resultat_", sl_label(h,tn))) 
      mdl <- readRDS(model_fname(h,tn))
  
      Sd  <- mdl$Sd
      Sf  <- mdl$Sf
      
      Sd_neighborhood <- nhbrhd(Sd)
      Sf_neighborhood <- nhbrhd(Sf)
      
      trancated_emg_res <- trancate_emg_result(G1 = res_emg$EMG_selected_locus$G1, 
                                               G2 = res_emg$EMG_selected_locus$G2,
                                               selection_order = res_emg$EMG_selected_locus$order,
                                               nmb_qtl = trancate_idx)
      
      emg_TP1 <- c(emg_TP1, length(intersect(unlist(Sf_neighborhood), trancated_emg_res$G1)))
      emg_TP2 <- c(emg_TP2, length(intersect(unlist(Sd_neighborhood), trancated_emg_res$G2)))

    }
    
  eagle_TP1_list[[trancate_idx]] <- eagle_TP1
  eagle_TP2_list[[trancate_idx]] <- eagle_TP2
  eagle_TP_list[[trancate_idx]]  <- eagle_TP1 + eagle_TP2
  eagle_FP_list[[trancate_idx]]  <- trancate_idx - (eagle_TP1 + eagle_TP2)
  
  emg_TP1_list[[trancate_idx]] <- emg_TP1
  emg_TP2_list[[trancate_idx]] <- emg_TP2
  emg_TP_list[[trancate_idx]]  <- emg_TP1 + emg_TP2
  emg_FP_list[[trancate_idx]]  <- trancate_idx - (emg_TP1 + emg_TP2)
}

eagle_TP <- matrix(unlist(eagle_TP_list), ncol = max_trancate_num, nrow = eagle_total_test_times)
eagle_FP <- matrix(unlist(eagle_FP_list), ncol = max_trancate_num, nrow = eagle_total_test_times)
emg_TP   <- matrix(unlist(emg_TP_list), ncol = max_trancate_num, nrow = emg_total_test_times)
emg_FP   <- matrix(unlist(emg_FP_list), ncol = max_trancate_num, nrow = emg_total_test_times)

```

#### TP

```{r}
library(ggplot2)

# nombre de TP en fonction du nombre de snps selectionnes 

plot(1:max_trancate_num, unlist(lapply(data.frame(emg_TP), max)),type = "l")
plot(1:max_trancate_num, unlist(lapply(data.frame(eagle_TP), max)),type = "l")

plot(1:max_trancate_num, unlist(lapply(data.frame(emg_TP), mean)),type = "l")
plot(1:max_trancate_num, unlist(lapply(data.frame(eagle_TP), mean)),type = "l")

# ROC Curve TPR and FPR

emg_precis <- unlist(lapply(data.frame(emg_TP), max)) / 20
emg_recall <- unlist(lapply(data.frame(emg_FP), min)) / 20
plot(emg_recall,emg_precis, type = "l", xlim=c(0,1), ylim=c(0,1),
     xlab = "Recall",ylab = "Precision",main = "ROC Curve")
```

# ROC Curve

```{r}
library(pROC)
# ROCr
# 
# examples : https://rpubs.com/Wangzf/pROC


```

