---
title: "R Notebook"
output: html_notebook
---

```{r echo=FALSE, message=FALSE}
library(MM4LMM)
library(sommer)
library(nnet)
library(Eagle)
library(parallel)
library(dplyr)
# library(tidyverse)

source("Eagle_Multi_Genomes.R")
```

#### load DT data

```{r}
data(DT_technow)
DT <- DT_technow

Mf <- Mf_technow
Md <- Md_technow

# Md <- (Md*2) - 1
# Mf <- (Mf*2) - 1
# Kf <- tcrossprod(Mf)/ncol(Mf)
# Kd <- tcrossprod(Md)/ncol(Md)

Zf <- class.ind(DT$flint)
Zf <- Zf[,rownames(Mf)]

Zd <- class.ind(DT$dent)
Zd <- Zd[,rownames(Md)]
```

#### Prepare for the simulation

```{r}
# H= S_G^2 / (S_G^2 + S_E^2)
h = 0.9 # fixe

# Y = Z1 U1 + Z2 U2 + E
nqtl.d = 10 # fixed
nqtl.f = 10 # fixed

# Sd.names <- colnames(Zd)[sample(1:ncol(Zd), nqtl.d)]
# Sf.names <- colnames(Zf)[sample(1:ncol(Zf), nqtl.f)]

# Sd <- sample(1:ncol(Md), nqtl.d) # fixed
# Sf <- sample(1:ncol(Mf), nqtl.f) # fixed

# vg1 <- 0.01
# vg2 <- 0.01

# adS <- seq(10,20,l=nqtl.d)
# # adS <- runif(nqtl.d, 10, 20)
# afS <- seq(10,20,l=nqtl.f)
# # afS <- runif(nqtl.d, 10, 20)
 
# Ud <- MdS %*% adS + Md_S %*% ad_S
# Uf <- MfS %*% afS + Mf_S %*% af_S
 
# Uh <- Zd %*% Ud + Zf %*% Uf
# vg <- var(Uh)

# sigma_E <- as.numeric(sqrt(vg*(1-h)/h))
```

#### constants

```{r}
PWD <- paste0(getwd(),"/Test_Result/")
label <- "[adS:%d-%d][afS:%d-%d][gamma=%.2f]"
simulation_times <- 100
# gamma <- 0.1
gamma <- 0
```

#### Generate dat file for Eagle

```{r}
S2 <- readRDS("Test_Result02/Ssample")
Sd <- S2$Sd
Sf <- S2$Sf

saveRDS(object = list("Sd" = Sd, "Sf" = Sf), paste0(PWD, "Ssample"))

# write.table(Mf, file = paste0(PWD,"Mf.dat"), col.names = FALSE, row.names =  FALSE, sep = " ")
# write.table(Md, file = paste0(PWD,"Md.dat"), col.names = FALSE, row.names =  FALSE, sep = " ")

# write.table(Zf, paste0(PWD,"Zf.dat"), row.names =  FALSE, col.names = FALSE, sep = " ", quote = FALSE)
# write.table(Zd, paste0(PWD,"Zd.dat"), row.names =  FALSE, col.names = FALSE, sep = " ", quote = FALSE)

# write.table(list("Trait" = Y), "trait.dat", row.names =  FALSE, sep = " ", quote = FALSE)
```

```{r echo=FALSE, message=FALSE}
Ss <- readRDS(paste0(PWD, "Ssample"))

Sd <- Ss$Sd
Sf <- Ss$Sf

Md_S <- Md[, - Sd]
Mf_S <- Mf[, - Sf]

ad_S <- rep(0,ncol(Md_S))
af_S <- rep(0,ncol(Mf_S))

MdS <- Md[, Sd]
MfS <- Mf[, Sf]


S <- c(1,5,10,20,40,60,100,140,180,220,260,300,350,400,500,600,800)

S <- c(20)

args_X <- list()

for ( s_idx in 1:length(S) ) {

  s <- S[s_idx]
  
  adS <- seq(s,s+nqtl.d,l=nqtl.d)
  afS <- seq(s,s+nqtl.f,l=nqtl.f)
  
  Ud <- MdS %*% adS + Md_S %*% ad_S
  Uf <- MfS %*% afS + Mf_S %*% af_S
  
  Uh <- Zd %*% Ud + Zf %*% Uf
  vg <- var(Uh)
  
  sigma_E <- as.numeric(sqrt(vg*(1-h)/h))
  
  s_label <- sprintf(label, adS[1], adS[nqtl.d], afS[1], afS[nqtl.f], gamma)
  
  for ( itr in 11:simulation_times) {
    
    E <- sigma_E * rnorm(length(DT$GY))
    Y <- Uh + E
    itn_label = paste0(s_label, "[tn=", itr, "]")
    write.table(list("Trait" = Y), paste0(PWD,"trait_",itn_label,".dat"), 
                row.names =  FALSE, sep = " ", quote = FALSE)
    
    args_X[[(s_idx-1)*simulation_times+itr]] <- list("adS" = adS, "afS" = afS,
                                                "s_label" = s_label, "label" = label, 
                                                "gamma" = gamma, "s" = s, "itr" = itr) 
  }
}

test_case <- function(X) {
  s       = X$s
  adS     = X$adS
  afS     = X$afS 
  s_label = X$s_label
  label   = X$label
  gamma   = X$gamma
  itr     = X$itr
  
  itn_label = paste0(s_label, "[tn=", itr, "]")
  # message(sprintf("Start test %d with s = %d", itr, s))
  # if (file.exists(paste0(PWD, "resultat_", itn_label))) {
  #   res <- readRDS(file = paste0(PWD, "resultat_", itn_label))
  #   
  #   Eagle_selected_locus_G1_history <- res$Eagle_selected_locus_G1_history 
  #   Eagle_selected_locus_G2_history <- res$Eagle_selected_locus_G2_history 
  #   EMG_selected_locus_history <- res$EMG_selected_locus_history
  #   eagle_excute_time_history <- res$eagle_excute_time_history
  #   emg_excute_time_history <- res$emg_excute_time_history
  # } else {
    
  if (DO_EAGLE) {
    tfname = paste0(PWD, "eagle_resultat_", itn_label)
    if (!file.exists(tfname)) {
      phenoObj <- ReadPheno(paste0(PWD,"trait_",itn_label,".dat"))
      Mf_genoObj <- ReadMarker(paste0(PWD,"Mf.dat"), type = "text", AA = 0, AB = 2, BB = 1)
      Md_genoObj <- ReadMarker(paste0(PWD,"Md.dat"), type = "text", AA = 0, AB = 2, BB = 1)
      
      Mf_Zmat <- ReadZmat(paste0(PWD,"Zf.dat"))
      Md_Zmat <- ReadZmat(paste0(PWD,"Zd.dat"))
      
      eagle_start_time <- Sys.time()
      Eagle_selected_locus_G1 <- AM(trait = "Trait", Zmat = Mf_Zmat, geno = Mf_genoObj, 
                                    pheno = phenoObj, ncpu = 48, lambda = gamma) # , maxit = 20, )
      Eagle_selected_locus_G2 <- AM(trait = "Trait", Zmat = Md_Zmat, geno = Md_genoObj, 
                                    pheno = phenoObj, ncpu = 48, lambda = gamma) # , maxit = 20)
      eagle_end_time <- Sys.time()
      
      saveRDS(list("Eagle_selected_locus_G1" = Eagle_selected_locus_G1$Indx, 
                   "Eagle_selected_locus_G2" = Eagle_selected_locus_G2$Indx, 
                   "eagle_excute_time" = eagle_end_time - eagle_start_time), 
              file = paste0(PWD, "eagle_resultat_", itn_label))
    }
  }
  
  if (DO_EMG) {
    tfname = paste0(PWD, "emg_resultat_", itn_label)
    # if (!file.exists(tfname)) {
      max_itr_num = 100
      Y <- read.csv(paste0(PWD,"trait_",itn_label,".dat"), sep = " ", header = TRUE)[,1]
        
      emg_start_time <- Sys.time()
      EMG_selected_locus <- EMG(Y = Y, G1 = Mf_technow*2, G2 = Md_technow*2, Z1 = Zf, Z2 = Zd, 
                  genome_names = c("Flint", "Dent"), gamma = gamma, max_itr_num = max_itr_num )
      emg_end_time <- Sys.time()
        
      saveRDS(list("EMG_selected_locus" = EMG_selected_locus, 
                     "emg_excute_time" = emg_end_time - emg_start_time), 
                  file = paste0(PWD, "emg_resultat_", itn_label))
    # }
  }
}

DO_EMG = FALSE
DO_EAGLE = TRUE

for (X in args_X) {
  test_case(X)
}

DO_EMG = TRUE
DO_EAGLE = FALSE

mclapply(args_X, test_case, mc.cores = getOption("mc.cores", 12L)) # mc.silent = TRUE, 
```
  
  
```{r}
Eagle_S_selected_locus_G1_history <- list()
Eagle_S_selected_locus_G2_history <- list()
EMG_S_selected_locus_history <- list()
eagle_S_excute_time_history <- c()
emg_S_excute_time_history <- c()

for ( s_idx in 1:length(S) ) {
  s <- S[s_idx]
  
  adS <- seq(s,s+nqtl.d,l=nqtl.d)
  afS <- seq(s,s+nqtl.f,l=nqtl.f)
  
  Ud <- MdS %*% adS + Md_S %*% ad_S
  Uf <- MfS %*% afS + Mf_S %*% af_S
  
  Uh <- Zd %*% Ud + Zf %*% Uf
  vg <- var(Uh)
  
  sigma_E <- as.numeric(sqrt(vg*(1-h)/h))
  
  s_label <- sprintf(label, adS[1], adS[nqtl.d], afS[1], afS[nqtl.f], gamma)
  
  Eagle_S_selected_locus_G1_history[[s_idx]] <- list()
  Eagle_S_selected_locus_G2_history[[s_idx]] <- list()
  EMG_S_selected_locus_history[[s_idx]] <- list()
  eagle_S_excute_time_history[[s_idx]] <- list()
  emg_S_excute_time_history[[s_idx]] <- list()
  
  for ( itr in 1:simulation_times) {
    itn_label = paste0(s_label, "[tn=", itr, "]") 
    print(itn_label)
    eagle_res <- readRDS(file = paste0(PWD, "eagle_resultat_", itn_label)) 
    emg_res <- readRDS(file = paste0(PWD, "emg_resultat_", itn_label)) 
    
    Eagle_S_selected_locus_G1_history[[s_idx]][[itr]] <- eagle_res$Eagle_selected_locus_G1 
    Eagle_S_selected_locus_G2_history[[s_idx]][[itr]] <- eagle_res$Eagle_selected_locus_G2 
    EMG_S_selected_locus_history[[s_idx]][[itr]] <- emg_res$EMG_selected_locus 
    eagle_S_excute_time_history[[s_idx]][[itr]] <- eagle_res$eagle_excute_time
    emg_S_excute_time_history[[s_idx]][[itr]] <- emg_res$emg_excute_time 
  }
}

```
  
  
```{r}
nmb_qtl = length(Sf) + length(Sd)

nb_radius <- 5

Sf_neighborhood5 <- unlist(lapply(Sf, function(x){seq(x-nb_radius,x+nb_radius)}))
Sd_neighborhood5 <- unlist(lapply(Sd, function(x){seq(x-nb_radius,x+nb_radius)}))

eagle_TP_list = list()
eagle_FP_list <- list()
eagle_FN_list <- list()

emg_TP_list <- list()
emg_FP_list <- list()
emg_FN_list <- list()

S <- c(1,5,10,20,40,60,100,140,180,220,260,300,350,400,500,600,800)

for ( s_idx in 1:length(S) ) {
  s <- S[s_idx]
  
  eagle_TP <- c()
  eagle_FP <- c()
  eagle_FN <- c()

  emg_TP <- c()
  emg_FP <- c()
  emg_FN <- c()
  
  for (itr in 1:simulation_times) {
    eagle_qtl_find1 = length(Eagle_S_selected_locus_G1_history[[s_idx]][[itr]])
    eagle_qtl_find2 = length(Eagle_S_selected_locus_G2_history[[s_idx]][[itr]])
    eagle_qtl_find = eagle_qtl_find1 + eagle_qtl_find2
    
    eagle_TP1 <- length(intersect(Sf_neighborhood5, Eagle_S_selected_locus_G1_history[[s_idx]][[itr]]))
    eagle_TP2 <- length(intersect(Sd_neighborhood5, Eagle_S_selected_locus_G2_history[[s_idx]][[itr]]))
    
    eagle_TP <- c(eagle_TP, eagle_TP1 + eagle_TP2)
    eagle_FP = c(eagle_FP, eagle_qtl_find - eagle_TP[itr])
    eagle_FN = c(eagle_FN, nmb_qtl - eagle_TP[itr])
    
    emg_qtl_find1 = length(EMG_S_selected_locus_history[[s_idx]][[itr]]$G1)
    emg_qtl_find2 = length(EMG_S_selected_locus_history[[s_idx]][[itr]]$G2)
    emg_qtl_find = emg_qtl_find1 + emg_qtl_find2
    
    emg_TP1 <- length(intersect(Sf_neighborhood5, EMG_S_selected_locus_history[[s_idx]][[itr]]$G1))
    emg_TP2 <- length(intersect(Sd_neighborhood5, EMG_S_selected_locus_history[[s_idx]][[itr]]$G2))
    
    emg_TP <- c(emg_TP, emg_TP1 + emg_TP2)
    emg_FP = c(emg_FP, emg_qtl_find - emg_TP[itr])
    emg_FN = c(emg_FN, nmb_qtl - emg_TP[itr])
  }
  
  eagle_TP_list[[s_idx]] <- eagle_TP
  eagle_FP_list[[s_idx]] <- eagle_FP
  eagle_FN_list[[s_idx]] <- eagle_FN

  emg_TP_list[[s_idx]] <- emg_TP
  emg_FP_list[[s_idx]] <- emg_FP
  emg_FN_list[[s_idx]] <- emg_FN
}
```

#### TP, FP, FN

```{r}
library(ggplot2)

S <- c(1,5,10,20,40,60,100,140,180,220,260,300,350,400,500,600,800)
a = rep(paste0(S), each=simulation_times)
algo = rep(c("eagle","emg"), each=10)
TP = c()

for ( s_idx in 1:length(S) ) {
  TP = c(TP, eagle_TP_list[[s_idx]])
  TP = c(TP, emg_TP_list[[s_idx]])
}

data_TP = data.frame(a, algo,  TP)

TP_mean <- data_TP %>% 
            group_by(a,algo) %>% 
            summarize(average = mean(TP)) %>% 
            ungroup()

TP_mean_eagle <- TP_mean %>% filter(algo=="eagle")
TP_mean_emg <- TP_mean %>% filter(algo=="emg")

ggplot(data_TP, aes(x=reorder(a, as.numeric(a)), y=TP, fill=algo), main = "True Positive") + geom_boxplot() + geom_point(data = TP_mean_eagle, mapping = aes(x = reorder(a, as.numeric(a)), y = average), color="red") + geom_line(data=TP_mean_eagle, mapping = aes(x = reorder(a, as.numeric(a)), y = average, group=1), colour = "red") + geom_point(data = TP_mean_emg, mapping = aes(x = reorder(a, as.numeric(a)), y = average), color="blue") + geom_line(data=TP_mean_emg, mapping = aes(x = reorder(a, as.numeric(a)), y = average, group=1), colour = "blue")

# plot(x = c(1:9)/10, y = unlist(lapply(eagle_TP_list, mean)), type = "l") 
# lines(x = c(1:9)/10, y = unlist(lapply(emg_TP_list, mean)), type = "l") 
       
FP= c()
for ( s_idx in 1:length(S) ) {
  FP = c(FP, eagle_FP_list[[s_idx]])
  FP = c(FP, emg_FP_list[[s_idx]])
}

data_FP = data.frame(a, algo,  FP)

FP_mean <- data_FP %>% 
            group_by(a,algo) %>% 
            summarize(average = mean(FP)) %>% 
            ungroup()

FP_mean_eagle <- FP_mean %>% filter(algo=="eagle")
FP_mean_emg <- FP_mean %>% filter(algo=="emg")

ggplot(data_FP, aes(x=reorder(a, as.numeric(a)), y=FP, fill=algo), main = "False Positive") + geom_boxplot() + geom_point(data = FP_mean_eagle, mapping = aes(x = reorder(a, as.numeric(a)), y = average), color="red") + geom_line(data=FP_mean_eagle, mapping = aes(x = reorder(a, as.numeric(a)), y = average, group=1), colour = "red") + geom_point(data = FP_mean_emg, mapping = aes(x = reorder(a, as.numeric(a)), y = average), color="blue") + geom_line(data=FP_mean_emg, mapping = aes(x = reorder(a, as.numeric(a)), y = average, group=1), colour = "blue")

FN= c()
for ( s_idx in 1:length(S) ) {
  FN = c(FN, eagle_FN_list[[s_idx]])
  FN = c(FN, emg_FN_list[[s_idx]])
}

data_FN = data.frame(a, algo,  FN)

FN_mean <- data_FN %>% 
            group_by(a,algo) %>% 
            summarize(average = mean(FN)) %>% 
            ungroup()

FN_mean_eagle <- FN_mean %>% filter(algo=="eagle")
# FN_mean_eagle <- bind_cols(average = FN_mean_eagle$average, gamma = as.numeric(FN_mean_eagle$gamma)-0.02)

FN_mean_emg <- FN_mean %>% filter(algo=="emg")
# FN_mean_emg <- bind_cols(average = FN_mean_emg$average, gamma = as.numeric(FN_mean_emg$gamma)+0.02)

ggplot(data_FP, aes(x=reorder(a, as.numeric(a)), y=FN, fill=algo), main = "False Positive") + geom_boxplot() + geom_point(data = FN_mean_eagle, mapping = aes(x = reorder(a, as.numeric(a)), y = average), color="red") + geom_line(data=FN_mean_eagle, mapping = aes(x = reorder(a, as.numeric(a)), y = average, group=1), colour = "red") + geom_point(data = FN_mean_emg, mapping = aes(x = reorder(a, as.numeric(a)), y = average), color="blue") + geom_line(data=FN_mean_emg, mapping = aes(x = reorder(a, as.numeric(a)), y = average, group=1), colour = "blue")
```


# ROC Curve

```{r}
TPR = function(TP,FN) TP/(TP+FN) 
FPR = function(FP,TN) FP/(FP+TN)

eagle_TPR = c()
eagle_FPR = c()

emg_TPR = c()
emg_FPR = c()

for (gamma_idx in 1:9) {
    eagle_TPR = c(eagle_TPR, mean(TPR(eagle_TP_list[[gamma_idx]],eagle_FP_list[[gamma_idx]])))
    eagle_FPR 
    emg_TPR   = c(emg_TPR,  mean(TPR(emg_TP_list[[gamma_idx]],emg_TP_list[[gamma_idx]])))
}

```

