---
title: "Compare to the results in presentation"
output: html_notebook
---

```{r echo=FALSE, message=FALSE}
library(MM4LMM)
library(sommer)
library(nnet)
library(Eagle)
library(parallel)
library(dplyr)
# library(tidyverse)

source("Eagle_Multi_Genomes.R")
```

#### load DT data

```{r}
data(DT_technow)
DT <- DT_technow

Mf <- Mf_technow
Md <- Md_technow

Zf <- class.ind(DT$flint)
Zf <- Zf[,rownames(Mf)]

Zd <- class.ind(DT$dent)
Zd <- Zd[,rownames(Md)]
```

#### Prepare for the simulation

```{r}
# H= S_G^2 / (S_G^2 + S_E^2)
h = 0.9 # fixe

# Y = Z1 U1 + Z2 U2 + E
nqtl.d = 10 # fixed
nqtl.f = 10 # fixed

```

#### constants

```{r}
PWD <- paste0(getwd(),"/Test_Result10/")
label <- "[adS:%d-%d][afS:%d-%d][gamma=%.2f]"
simulation_times <- 10
max_itr_num <- 80
gamma <- 0
```

```{r echo=FALSE, message=FALSE}

Ss <- readRDS(file = paste0(PWD, "Ssample"))
Sd <- Ss$Sd
Sf <- Ss$Sf
rm(Ss)

Md_S <- Md[, - Sd]
Mf_S <- Mf[, - Sf]

ad_S <- rep(0,ncol(Md_S))
af_S <- rep(0,ncol(Mf_S))

MdS <- Md[, Sd]
MfS <- Mf[, Sf]

a_ <- 20

adS <- seq(a_,a_+nqtl.d,l=nqtl.d)
afS <- seq(a_,a_+nqtl.f,l=nqtl.f)
Ud <- MdS %*% adS + Md_S %*% ad_S
Uf <- MfS %*% afS + Mf_S %*% af_S
Uh <- Zd %*% Ud + Zf %*% Uf
vg <- var(Uh)

sigma_E <- as.numeric(sqrt(vg*(1-h)/h))

s_label <- sprintf(label, adS[1], adS[nqtl.d], afS[1], afS[nqtl.f], gamma)

args_X <- list()

for ( itr in 1:simulation_times) {
  
  E <- sigma_E * rnorm(length(DT$GY))
  Y <- Uh + E
  itn_label = paste0(s_label, "[tn=", itr, "]")
  write.table(list("Trait" = Y), paste0(PWD,"trait_",itn_label,".dat"), 
              row.names =  FALSE, sep = " ", quote = FALSE)
  
  args_X[[itr]] <- list("adS" = adS, "afS" = afS, "s_label" = s_label, 
                        "gamma" = gamma, "itr" = itr, 
                        "max_itr_num" = max_itr_num) 
}


test_case <- function(X) {
  adS     = X$adS
  afS     = X$afS 
  s_label = X$s_label
  gamma   = X$gamma
  itr     = X$itr
  max_itr_num = X$max_itr_num
  
  itn_label = paste0(s_label, "[tn=", itr, "]")
    
  if (DO_EAGLE) {
    tfname = paste0(PWD, "eagle_resultat_", itn_label)
    if (!file.exists(tfname)) {
      phenoObj <- ReadPheno(paste0(PWD,"trait_",itn_label,".dat"))
      Mf_genoObj <- ReadMarker(paste0(PWD,"Mf.dat"), type = "text", AA = 0, AB = 2, BB = 1)
      Md_genoObj <- ReadMarker(paste0(PWD,"Md.dat"), type = "text", AA = 0, AB = 2, BB = 1)
      
      Mf_Zmat <- ReadZmat(paste0(PWD,"Zf.dat"))
      Md_Zmat <- ReadZmat(paste0(PWD,"Zd.dat"))
      
      eagle_start_time <- Sys.time()
      Eagle_selected_locus_G1 <- AM(trait = "Trait", Zmat = Mf_Zmat, geno = Mf_genoObj, 
                                    pheno = phenoObj, ncpu = 48, lambda = gamma, maxit = ceiling(max_itr_num/2), fixit = TRUE)
      Eagle_selected_locus_G2 <- AM(trait = "Trait", Zmat = Md_Zmat, geno = Md_genoObj, 
                                    pheno = phenoObj, ncpu = 48, lambda = gamma, maxit = ceiling(max_itr_num/2), fixit = TRUE)
      eagle_end_time <- Sys.time()
      
      saveRDS(list("Eagle_selected_locus_G1" = Eagle_selected_locus_G1$Indx, 
                   "Eagle_selected_locus_G2" = Eagle_selected_locus_G2$Indx, 
                   "eagle_excute_time" = eagle_end_time - eagle_start_time), 
              file = paste0(PWD, "eagle_resultat_", itn_label))
    }
  }
  
  if (DO_EMG) {
    tfname = paste0(PWD, "emg_resultat_", itn_label)
    if (!file.exists(tfname)) {
      Y <- read.csv(paste0(PWD,"trait_",itn_label,".dat"), sep = " ", header = TRUE)[,1]
        
      emg_start_time <- Sys.time()
      EMG_selected_locus <- EMG(Y = Y, G1 = Mf_technow*2, G2 = Md_technow*2, Z1 = Zf, Z2 = Zd, 
                  genome_names = c("Flint", "Dent"), gamma = gamma, max_itr_num = max_itr_num )
      emg_end_time <- Sys.time()
        
      saveRDS(list("EMG_selected_locus" = EMG_selected_locus, 
                     "emg_excute_time" = emg_end_time - emg_start_time), 
                  file = paste0(PWD, "emg_resultat_", itn_label))
    }
  }
}

```

```{r}

DO_EMG = TRUE
DO_EAGLE = FALSE

mclapply(args_X, test_case, mc.cores = getOption("mc.cores", 12L)) # mc.silent = TRUE, 

DO_EMG = FALSE
DO_EAGLE = TRUE

for (X in args_X) {
  message(sprintf("iteration number %d", X$itr))
  test_case(X)
}

```

#### courbe de nombre de TP en fonction de snps sélectionnés 

```{r}
Ss <- readRDS(file = paste0(PWD, "Ssample"))

Sd <- Ss$Sd
Sf <- Ss$Sf

a_ <- 20

adS <- seq(a_,a_+nqtl.d,l=nqtl.d)
afS <- seq(a_,a_+nqtl.f,l=nqtl.f)

nb_radius <- 5

Sf_neighborhood <- lapply(Sf, function(x){seq(x-nb_radius,x+nb_radius)})
Sd_neighborhood <- lapply(Sd, function(x){seq(x-nb_radius,x+nb_radius)})

trancate_eagle_result <- function(G1, G2, nmb_qtl) {
  if (nmb_qtl >= length(G1)+length(G2)) {
    return(list("G1" = G1, "G2" = G2))
  }
  
  G1_count = ceiling(nmb_qtl/2)
  
  if (G1_count < length(G1)) {
    return(list("G1" = G1[1:G1_count], "G2" = G2[1:(nmb_qtl - G1_count)]))
  }
  
  return(list("G1" = G1, "G2" = G2[1:nmb_qtl-length(G1)]))
  
}

trancate_emg_result <- function(G1, G2, selection_order, nmb_qtl) {
  if (nmb_qtl >= length(selection_order)) {
    return(list("G1" = G1, "G2" = G2))
  }
  
  G1_count = sum(selection_order[1:nmb_qtl] == 1)
  
  if (G1_count == 0) return(list("G1" = c(), "G2" = G2[1:nmb_qtl]))
  if (G1_count == nmb_qtl) return(list("G1" = G1[1:G1_count], "G2" = c()))
  return(list("G1" = G1[1:G1_count], "G2" = G2[1:(nmb_qtl-G1_count)]))
}

eagle_TP1_list = list()
eagle_TP2_list = list()

eagle_TP_list = list()

eagle_FP_list <- list()
eagle_FN_list <- list()

emg_TP1_list <- list()
emg_TP2_list <- list()

emg_TP_list <- list()

emg_FP_list <- list()
emg_FN_list <- list()

max_trancate_num <- 50
total_test_num   <- 10

for (trancate_idx in 1:max_trancate_num) {
    
    eagle_TP1 <- c()
    eagle_TP2 <- c()
    
    eagle_FP <- c()
    eagle_FN <- c()
  
    emg_TP1 <- c()
    emg_TP2 <- c()
    
    emg_FP <- c()
    emg_FN <- c()
    
    for (simulation_num in 1:total_test_num) {
      
      s_label <- sprintf(label, adS[1], adS[nqtl.d], afS[1], afS[nqtl.f], gamma)
      
      itn_label = paste0(s_label, "[tn=", simulation_num, "]")
      
      res_eagle <- readRDS(file = paste0(PWD, "eagle_resultat_", itn_label))
      
      trancated_eagle_res <- trancate_eagle_result(G1 = res_eagle$Eagle_selected_locus_G1[2:length(res_eagle$Eagle_selected_locus_G1)],
                                                   G2 = res_eagle$Eagle_selected_locus_G2[2:length(res_eagle$Eagle_selected_locus_G2)],
                                                   nmb_qtl = trancate_idx)
  
      res_emg <- readRDS(file = paste0(PWD, "emg_resultat_", itn_label))
      
      trancated_emg_res <- trancate_emg_result(G1 = res_emg$EMG_selected_locus$G1, 
                                               G2 = res_emg$EMG_selected_locus$G2,
                                               selection_order = res_emg$EMG_selected_locus$order,
                                               nmb_qtl = trancate_idx)
      
      # EMG_selected_locus_order <- res_emg$order[1:trancate_idx]
    
      eagle_TP1 <- c(eagle_TP1, length(intersect(unlist(Sf_neighborhood), trancated_eagle_res$G1)))
      eagle_TP2 <- c(eagle_TP2, length(intersect(unlist(Sd_neighborhood), trancated_eagle_res$G2)))
      
      emg_TP1 <- c(emg_TP1, length(intersect(unlist(Sf_neighborhood), trancated_emg_res$G1)))
      emg_TP2 <- c(emg_TP2, length(intersect(unlist(Sd_neighborhood), trancated_emg_res$G2)))

    
    }
    
  eagle_TP1_list[[trancate_idx]] <- eagle_TP1
  eagle_TP2_list[[trancate_idx]] <- eagle_TP2
  eagle_TP_list[[trancate_idx]]  <- eagle_TP1 + eagle_TP2
  eagle_FP_list[[trancate_idx]]  <- trancate_idx - (eagle_TP1 + eagle_TP2)
  
  emg_TP1_list[[trancate_idx]] <- emg_TP1
  emg_TP2_list[[trancate_idx]] <- emg_TP2
  emg_TP_list[[trancate_idx]]  <- emg_TP1 + emg_TP2
  emg_FP_list[[trancate_idx]]  <- trancate_idx - (emg_TP1 + emg_TP2)
}

eagle_TP1 <- matrix(unlist(eagle_TP1_list), ncol = max_trancate_num, nrow = total_test_num)
eagle_TP2 <- matrix(unlist(eagle_TP2_list), ncol = max_trancate_num, nrow = total_test_num)
eagle_TP  <- eagle_TP1 + eagle_TP2

emg_TP1 <- matrix(unlist(emg_TP1_list), ncol = max_trancate_num, nrow = total_test_num)
emg_TP2 <- matrix(unlist(emg_TP2_list), ncol = max_trancate_num, nrow = total_test_num)
emg_TP  <- emg_TP1 + emg_TP2

```

#### TP

```{r}
library(ggplot2)


total_selected_snps_num = rep(paste0(1:max_trancate_num), each = total_test_num*2)
algo = rep(c("eagle","emg"), each = total_test_num)
TP = c()

for ( t_idx in 1:max_trancate_num ) {
  TP = c(TP, eagle_TP_list[[t_idx]])
  TP = c(TP, emg_TP_list[[t_idx]])
}

data_TP = data.frame(total_selected_snps_num, algo,  TP)

TP_mean <- data_TP %>% 
            group_by(total_selected_snps_num,algo) %>% 
            summarize(average = mean(TP)) %>% 
            ungroup()

TP_mean_eagle <- TP_mean %>% filter(algo=="eagle")
TP_mean_emg <- TP_mean %>% filter(algo=="emg")

# png(filename="TP.png", width=1200, height=600)

ggplot(data_TP, aes(x=reorder(total_selected_snps_num, as.numeric(total_selected_snps_num)), y=TP, fill=algo), main = "True Positive") + geom_boxplot() + geom_point(data = TP_mean_eagle, mapping = aes(x = reorder(total_selected_snps_num, as.numeric(total_selected_snps_num)), y = average), color="red") + geom_line(data=TP_mean_eagle, mapping = aes(x = reorder(total_selected_snps_num, as.numeric(total_selected_snps_num)), y = average, group=1), colour = "red") + geom_point(data = TP_mean_emg, mapping = aes(x = reorder(total_selected_snps_num, as.numeric(total_selected_snps_num)), y = average), color="blue") + geom_line(data=TP_mean_emg, mapping = aes(x = reorder(total_selected_snps_num, as.numeric(total_selected_snps_num)), y = average, group=1), colour = "blue")

# dev.off()


FP= c()

for ( t_idx in 1:max_trancate_num ) {
  FP = c(FP, eagle_FP_list[[t_idx]])
  FP = c(FP, emg_FP_list[[t_idx]])
}

data_FP = data.frame(total_selected_snps_num, algo,  FP)

FP_mean <- data_FP %>% 
            group_by(total_selected_snps_num,algo) %>% 
            summarize(average = mean(FP)) %>% 
            ungroup()

FP_mean_eagle <- FP_mean %>% filter(algo=="eagle")
FP_mean_emg <- FP_mean %>% filter(algo=="emg")

# png(filename="FP.png", width=1200, height=600)

ggplot(data_FP, aes(x=reorder(total_selected_snps_num, as.numeric(total_selected_snps_num)), y=FP, fill=algo), main = "False Positive") + geom_boxplot() + geom_point(data = FP_mean_eagle, mapping = aes(x = reorder(total_selected_snps_num, as.numeric(total_selected_snps_num)), y = average), color="red") + geom_line(data=FP_mean_eagle, mapping = aes(x = reorder(total_selected_snps_num, as.numeric(total_selected_snps_num)), y = average, group=1), colour = "red") + geom_point(data = FP_mean_emg, mapping = aes(x = reorder(total_selected_snps_num, as.numeric(total_selected_snps_num)), y = average), color="blue") + geom_line(data=FP_mean_emg, mapping = aes(x = reorder(total_selected_snps_num, as.numeric(total_selected_snps_num)), y = average, group=1), colour = "blue")

# dev.off()
```
#### courbe de nombre de TP en fonction de snps sélectionnés 

```{r}
# hs <- c(0.5, 0.7, 0.9)
# bs <- c(0.45, 0.65) # 0.15 is impossible
GM <- read.csv(paste0(getwd(),"/GeneticMap.xls"))
Ss <- readRDS(file = paste0(PWD, "Ssample"))
Sd <- Ss$Sd
Sf <- Ss$Sf
library(sommer)
data(DT_technow)
DT <- DT_technow

Mf <- Mf_technow
Md <- Md_technow

simulation_num <- 10

nqtl.d = 10 # fixed
nqtl.f = 10 # fixed
a_ <- 20

adS <- seq(a_,a_+nqtl.d,l=nqtl.d)
afS <- seq(a_,a_+nqtl.f,l=nqtl.f)

h = 0.9
b = 1

window_size <- 10000000
max_trancate_num <- 80
neighborhood_radius <- window_size/2

DO_EAGLE <- TRUE
DO_EMG <- TRUE
eagle_total_test_times <- 10
emg_total_test_times   <- 10

# method = "ML"
# neighborhoods
# nhbrhd <- function(S, nb_radius=5) sapply(S, function(x){seq(x-nb_radius,x+nb_radius)})
nhbrhds <- function(S, nb_radius=500000) {
  
  lapply(S, function(x){
    
    neighbors <- c(x)
    chrom <- GM$chrom[x]
    pos   <- GM$pos[x]
    x_l <- x - 1
    x_r <- x + 1
    
    while (x_l > 0 && GM$chrom[x_l] == chrom && GM$pos[x_l] >= pos - nb_radius) {
      neighbors <- c(x_l, neighbors)
      x_l <- x_l - 1
    }
    
    while (x_r <= nrow(GM) && GM$chrom[x_r] == chrom && GM$pos[x_r] <= pos + nb_radius) {
      neighbors <- c(neighbors, x_r)
      x_r <- x_r + 1
    }
    
    return(neighbors)
  })
}

count_TP <- function(X, neighborhoods) {
  pred.tps <- intersect(unlist(neighborhoods), unlist(X))
  ture.tps.idx <- c()
  for (tp in pred.tps) {
    ture.tps.idx <- c(ture.tps.idx, sapply(1:length(neighborhoods), FUN = function(n){
      if (tp %in% neighborhoods[[n]]) return(n)
    }))
  }
  ture.tps.idx <- unique(Filter(Negate(is.null), ture.tps.idx))
  return(list("pred" = pred.tps, 
              "true" = ture.tps.idx,
              "p.count" = length(pred.tps),
              "t.count" = length(ture.tps.idx)))
}

trancate_eagle_result <- function(G1, G2, nmb_qtl) {

  if (nmb_qtl >= length(G1)+length(G2)) {
    return(list("G1" = G1, "G2" = G2))
  }
  
  G1_count = ceiling(nmb_qtl/2)
  
  if (G1_count < length(G1)) {
    return(list("G1" = G1[1:G1_count], "G2" = G2[1:(nmb_qtl - G1_count)]))
  }
  
  tryCatch({
    return(list("G1" = G1, "G2" = G2[1:(nmb_qtl-length(G1))]))
  }, error = function(cond) {
    print(cond)
    print(sprintf("[ERROR] length(G1): %d, length(G2): %d, nmb_qtl: %d",length(G1), length(G2), nmb_qtl))
  })
}

trancate_emg_result <- function(G1, G2, selection_order, nmb_qtl) {
  if (nmb_qtl >= length(selection_order)) {
    return(list("G1" = G1, "G2" = G2))
  }
  
  G1_count = sum(selection_order[1:nmb_qtl] == 1)
  
  if (G1_count == 0) return(list("G1" = c(), "G2" = G2[1:nmb_qtl]))
  if (G1_count == nmb_qtl) return(list("G1" = G1[1:G1_count], "G2" = c()))
  return(list("G1" = G1[1:G1_count], "G2" = G2[1:(nmb_qtl-G1_count)]))
}

eagle_TP1_list <- list()
eagle_TP2_list <- list()
eagle_TP_list  <- list()

eagle_FP1_list <- list()
eagle_FP2_list <- list()
eagle_FP_list  <- list()


emg_TP1_list <- list()
emg_TP2_list <- list()
emg_TP_list  <- list()

emg_FP1_list <- list()
emg_FP2_list <- list()
emg_FP_list  <- list()

# Load Model informations and Test Results

model_list   <- list()
res_eag_list <- list()
res_emg_list <- list()
Sd_neighborhood <- list()
Sf_neighborhood <- list()

for (tn in c(1:simulation_times)) {
  model_list[[tn]] <- readRDS(file = paste0(PWD, "Ssample"))
  Sd_neighborhood[[tn]] <- nhbrhds(model_list[[tn]]$Sd, neighborhood_radius)
  Sf_neighborhood[[tn]] <- nhbrhds(model_list[[tn]]$Sf, neighborhood_radius)
}

Sd_nghb_count <- length(unlist(Sd_neighborhood)) / simulation_times
Sf_nghb_count <- length(unlist(Sf_neighborhood)) / simulation_times

if (DO_EAGLE) {
  for (tn in c(1:eagle_total_test_times)) {
      s_label <- sprintf(label, adS[1], adS[nqtl.d], afS[1], afS[nqtl.f], gamma)
      itn_label <- paste0(s_label, "[tn=", simulation_num, "]")
      res_eag_list[[tn]] <- readRDS(file = paste0(PWD, "eagle_resultat_", itn_label))
      # res_eag_list[[tn]] <- readRDS(file = paste0(PWD, "Eagle_Results/eagle_resultat_", sl_label(h,b,tn)))
  }
}

if (DO_EMG) {
  for (tn in c(1:emg_total_test_times)) {
      s_label <- sprintf(label, adS[1], adS[nqtl.d], afS[1], afS[nqtl.f], gamma)
      itn_label <- paste0(s_label, "[tn=", simulation_num, "]")
      res_emg_list[[tn]] <- readRDS(file = paste0(PWD, "emg_resultat_", itn_label))
      # res_emg_list[[tn]] <- readRDS(file = paste0(PWD, "EMG_Results/emg_resultat_", sl_label(h,b,tn), "[Method=Reml]"))
  }
}

for (trancate_idx in 1:max_trancate_num) {
    
    eagle_TP1 <- c()
    eagle_TP2 <- c()
    
    eagle_FP1 <- c()
    eagle_FP2 <- c()
  
    emg_TP1 <- c()
    emg_TP2 <- c()
    
    emg_FP1 <- c()
    emg_FP2 <- c()
    
    if (DO_EAGLE) {
      for (tn in c(1:eagle_total_test_times)) {
          
          trancated_eagle_res <- trancate_eagle_result(G1 = res_eag_list[[tn]]$Eagle_selected_locus_G1[2:length(res_eag_list[[tn]]$Eagle_selected_locus_G1)],
                                                       G2 = res_eag_list[[tn]]$Eagle_selected_locus_G2[2:length(res_eag_list[[tn]]$Eagle_selected_locus_G2)],
                                                       nmb_qtl = trancate_idx)
      
          TP1 <- count_TP(trancated_eagle_res$G1, Sf_neighborhood[[tn]])
          TP2 <- count_TP(trancated_eagle_res$G2, Sd_neighborhood[[tn]])
          
          eagle_TP1 <- c(eagle_TP1, TP1$t.count)
          eagle_TP2 <- c(eagle_TP2, TP2$t.count)
          
          eagle_FP1 <- c(eagle_FP1, trancate_idx - TP1$p.count)
          eagle_FP2 <- c(eagle_FP2, trancate_idx - TP2$p.count)
        }
    }
    
    if (DO_EMG) {
      for (tn in c(1:emg_total_test_times)) {
        
        trancated_emg_res <- trancate_emg_result(G1 = res_emg_list[[tn]]$EMG_selected_locus$G1, 
                                                 G2 = res_emg_list[[tn]]$EMG_selected_locus$G2,
                                                 selection_order = res_emg_list[[tn]]$EMG_selected_locus$order,
                                                 nmb_qtl = trancate_idx)
        
        TP1 <- count_TP(trancated_emg_res$G1, Sf_neighborhood[[tn]])
        TP2 <- count_TP(trancated_emg_res$G2, Sd_neighborhood[[tn]])
        
        emg_TP1 <- c(emg_TP1, TP1$t.count)
        emg_TP2 <- c(emg_TP2, TP2$t.count)
        
        # emg_TP1 <- c(emg_TP1, TP1$p.count)
        # emg_TP2 <- c(emg_TP2, TP2$p.count)
        
        emg_FP1 <- c(emg_FP1, trancate_idx - TP1$p.count)
        emg_FP2 <- c(emg_FP2, trancate_idx - TP2$p.count)
        
      }
    }
    
  eagle_TP1_list[[trancate_idx]] <- eagle_TP1
  eagle_TP2_list[[trancate_idx]] <- eagle_TP2
  eagle_TP_list[[trancate_idx]]  <- eagle_TP1 + eagle_TP2
  
  eagle_FP1_list[[trancate_idx]] <- eagle_FP1
  eagle_FP2_list[[trancate_idx]] <- eagle_FP2
  eagle_FP_list[[trancate_idx]]  <- eagle_FP1 + eagle_FP2

  emg_TP1_list[[trancate_idx]] <- emg_TP1
  emg_TP2_list[[trancate_idx]] <- emg_TP2
  emg_TP_list[[trancate_idx]]  <- emg_TP1 + emg_TP2
  
  emg_FP1_list[[trancate_idx]] <- emg_FP1
  emg_FP2_list[[trancate_idx]] <- emg_FP2
  emg_FP_list[[trancate_idx]]  <- emg_FP1 + emg_FP2
  
}

eagle_TP1 <- matrix(unlist(eagle_TP1_list), ncol = max_trancate_num, nrow = eagle_total_test_times)
eagle_FP1 <- matrix(unlist(eagle_FP1_list), ncol = max_trancate_num, nrow = eagle_total_test_times)

eagle_TP2 <- matrix(unlist(eagle_TP2_list), ncol = max_trancate_num, nrow = eagle_total_test_times)
eagle_FP2 <- matrix(unlist(eagle_FP2_list), ncol = max_trancate_num, nrow = eagle_total_test_times)

eagle_TP <- matrix(unlist(eagle_TP_list), ncol = max_trancate_num, nrow = eagle_total_test_times)
eagle_FP <- matrix(unlist(eagle_FP_list), ncol = max_trancate_num, nrow = eagle_total_test_times)

emg_TP1   <- matrix(unlist(emg_TP1_list), ncol = max_trancate_num, nrow = emg_total_test_times)
emg_FP1   <- matrix(unlist(emg_FP1_list), ncol = max_trancate_num, nrow = emg_total_test_times)

emg_TP2   <- matrix(unlist(emg_TP2_list), ncol = max_trancate_num, nrow = emg_total_test_times)
emg_FP2   <- matrix(unlist(emg_FP2_list), ncol = max_trancate_num, nrow = emg_total_test_times)

emg_TP   <- matrix(unlist(emg_TP_list), ncol = max_trancate_num, nrow = emg_total_test_times)
emg_FP   <- matrix(unlist(emg_FP_list), ncol = max_trancate_num, nrow = emg_total_test_times)
```

#### Plots

```{r}
library(ggplot2)

# nombre de TP en fonction du nombre de snps selectionnes 

plot(1:max_trancate_num, unlist(lapply(data.frame(emg_TP), max)),type = "l", ylim = c(0,nqtl.d +nqtl.f), col = "red",
     xlab = "selected SNPs number", ylab = "True Positive", main = sprintf("EMG MAX heritability=%.2f balance=%.2f window size=%d",h,b,window_size))
lines(1:max_trancate_num, unlist(lapply(data.frame(eagle_TP), max)), col = "black")
legend("topleft", legend=c("emg total", "eagle total"), col=c("red", "black"), lty = 1:2, cex=0.8)

plot(1:max_trancate_num, unlist(lapply(data.frame(eagle_TP1), max)),type = "l", ylim = c(0,nqtl.d +nqtl.f), col = "red",
     xlab = "selected SNPs number", ylab = "True Positive", main = sprintf("EAGLE MAX heritability=%.2f balance=%.2f window size=%d",h,b,window_size))
lines(1:max_trancate_num, unlist(lapply(data.frame(eagle_TP2), max)), col = "blue")
lines(1:max_trancate_num, unlist(lapply(data.frame(emg_TP1), max)), col = "yellow")
lines(1:max_trancate_num, unlist(lapply(data.frame(emg_TP2), max)), col = "black")
legend("topleft", legend=c("eagle-flint", "eagle-dent", "emg-flint", "emg-dent"), col=c("red", "blue", "yellow", "black"), lty = 1:2, cex=0.8)

plot(1:max_trancate_num, unlist(lapply(data.frame(emg_TP), mean)),type = "l", ylim = c(0,nqtl.d +nqtl.f), col = "red",
     xlab = "selected SNPs number", ylab = "True Positive", main = sprintf("EMG MEAN heritability=%.2f balance=%.2f window size=%d",h,b,window_size))
lines(1:max_trancate_num, unlist(lapply(data.frame(eagle_TP), mean)), col = "black")
legend("topleft", legend=c("emg total", "eagle total"), col=c("red", "black"), lty = 1:2, cex=0.8)

plot(1:max_trancate_num, unlist(lapply(data.frame(eagle_TP1), mean)),type = "l", ylim = c(0,nqtl.d +nqtl.f), col = "red",
     xlab = "selected SNPs number", ylab = "True Positive", main = sprintf("EAGLE MEAN heritability=%.2f balance=%.2f window size=%d",h,b,window_size))
lines(1:max_trancate_num, unlist(lapply(data.frame(eagle_TP2), mean)), col = "blue")
lines(1:max_trancate_num, unlist(lapply(data.frame(emg_TP1), mean)), col = "yellow")
lines(1:max_trancate_num, unlist(lapply(data.frame(emg_TP2), mean)), col = "black")
legend("topleft", legend=c("eagle-flint", "eagle-dent", "emg-flint", "emg-dent"), col=c("red", "blue", "yellow", "black"), lty = 1:2, cex=0.8)

# AUC: Area Under the Curve
auc <- function(ratio_list) {
  return(sum(ratio_list)/length(ratio_list))
}

# ROC Curve TPR and FPR

# TPR = TP / P
TPR_EMG  <- unlist(lapply(data.frame(emg_TP), mean))  / (nqtl.f + nqtl.d)
TPR_EMG1 <- unlist(lapply(data.frame(emg_TP1), mean)) / nqtl.f
TPR_EMG2 <- unlist(lapply(data.frame(emg_TP2), mean)) / nqtl.d 

# FPR = FP / N
FPR_EMG  <- unlist(lapply(data.frame(emg_FP), mean)) / (ncol(Mf) + ncol(Md) - Sf_nghb_count - Sd_nghb_count)
FPR_EMG1 <- unlist(lapply(data.frame(emg_FP1), mean)) / (ncol(Mf) - Sf_nghb_count)
FPR_EMG2 <- unlist(lapply(data.frame(emg_FP2), mean)) / (ncol(Md) - Sd_nghb_count)

# TPR = TP / P
TPR_EAG  <- unlist(lapply(data.frame(eagle_TP), mean))  / (nqtl.d +nqtl.f)
TPR_EAG1 <- unlist(lapply(data.frame(eagle_TP1), mean)) / nqtl.f
TPR_EAG2 <- unlist(lapply(data.frame(eagle_TP2), mean)) / nqtl.d

# FPR = FP / N
FPR_EAG  <- unlist(lapply(data.frame(eagle_FP), mean))  / (ncol(Mf) + ncol(Md) - Sf_nghb_count - Sd_nghb_count)
FPR_EAG1 <- unlist(lapply(data.frame(eagle_FP1), mean)) / (ncol(Mf) - Sf_nghb_count)
FPR_EAG2 <- unlist(lapply(data.frame(eagle_FP2), mean)) / (ncol(Md) - Sd_nghb_count)

plot(FPR_EMG,TPR_EMG, type = "l", xlim=c(0,0.0025), ylim=c(0,1), xlab = "FPR (False Positive Rate)",ylab = "TPR (True Positive Rate)", main = sprintf("EMG ROC Curve heritability=%.2f balance=%.2f window size=%d",h,b,window_size), col = "red")
lines(FPR_EAG,TPR_EAG, col="black")
legend("topleft", legend=c("emg total", "eagle total"), col=c("red", "black"), lty = 1:2, cex=0.8)

plot(FPR_EMG1,TPR_EMG1, type = "l", xlim=c(0,0.0025), ylim=c(0,1), xlab = "FPR (False Positive Rate)",ylab = "TPR (True Positive Rate)", main = sprintf("EAGLE ROC Curve heritability=%.2f balance=%.2f window size=%d",h,b,window_size), col = "red")
lines(FPR_EMG2,TPR_EMG2, col="black")
lines(FPR_EAG1,TPR_EAG1, col="blue")
lines(FPR_EAG2,TPR_EAG2, col="yellow")
legend("topleft", legend=c("emg-flint", "emg-dent", "eagle-flint", "eagle-dent"), col=c("red", "black", "blue", "yellow"), lty = 1:2, cex=0.8)

```
